language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: K0U+5TMcKmL57jqe+T3HMGLrAixFCCmu4ojZsT6rwBPMAKzBx/vllf+8luJIXhP5cYbCN0YOIBPuUolYtcG5XPWKEfeDuzyd7m6X3iLBwNQNA/r+CEWDs7/3sJoQhCcKWB93tIBJRZCA0g7xbLN3ZBrusmeoi8YA0eB31TuAxXLmlx31Sgq/EE8VMxUsqi4sp9krmw3ssGgMd7LRYqoyls8/d9+Z3UGIV6q2YJZMRcJ3HhZMAKSbHHFb1on9aTeLDxhmJ7OIe0RXkbc3O/8G2HU1wWclaHHzWFt9cKoUuDjmdad1AAy5XgyKDNirOkdTZh2YoVCBPzr5LJ0wMqHqsqD9zEt8uOmk3W0E6tiPNjJ9P48qfhqu4uJvhz5OGu9Nq8tCzhzZ4kBL/Pxq9be6rbQ45yibXphEAcgDDxWeIVXCq7exJjJuBYtKbMNPAkBbhoT5u+bckrJuIbAyOXGpIwqAmgMlHBWGQtIuwqo6NeeP9IbfVyyk4wwN+qqEVbGvofvvjhrzTjZvFrQUz5oPCyPsIAdzCTD2FZ+zrOxiskarkqRraxoXVv6lnIpoHX/qs4YYdC7hcaVKc9ryWgWZE9cEdPuF8JAXaD4RorfiIDwjmIVl2JheY+NwpNFM8nY/zhQNbqA+igIjwZyF7oJ6HzW57EFl7N3ulO3MdTUn73Y=
  app:
    master: raptor-ads-staging
    production: raptor-ads-production
