language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: YytzvXOhzs9vrkAMUtwmmUikwxT8WmwtxjPtvQrPLe3fg9dG16PKBOMbAcL61c154PDFe4YkTI4Us/lm0uAMaRN/rQtyJ9X9ciDSTM0hmpfpNi079VqMSsUrglJcHih9PJ9ROjfXR2fYENsS9d2y24+nlNIWkPbKSUcama1rZi9pU63xvtPgZswWtxo4gl3lPNFomAD6AQDbwKoedpm9XVejq1eVI80cTUPNXel19P23q+JydycnZO8PD/s125/pM4vSRNFaz4cvXbw9eIq0FRMlKMXh1fd+rCYscBQr+/jveacW2CN2YfTiVONk4YdojxtOUSHMUm55+ohZwxMgkA+hsqtr+0k9Ln8Isn9D6/TnDRVmiRI9eSf8AVmooEZvoUifluhwPneyCGFFFm4w5RaCuVyyAsmfmkolTYQTIuIXy9gF3uL2I1u8zgKljZbZvVb5nkM5cwjFBWuF1ZpEL9YMT8qAMFnttA3YDPiU/zZo6WUx70rpiu+IuRR+nXYBKrI6/RbErmNEh0kWJ2CFbdW41EJHKQoksFvDpCpIqmOdYhrDVdFf5BVmXUqK5kMrB8z+QngqYaPabT3ufSyd1k9lJDuPYBn9idbBjPGEoGwUQRHvhGGkL4ExO71BTk/p+/jkppLmz3aOgoF7TJgTpk6OjJXgmZ7s9PBI7Ux9aF4=
  app:
    master: raptor-ads-staging
    production: raptor-ads-production
